[workspace]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.93.1"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/DenisGorbachev/workflowy-api"
repository = "https://github.com/DenisGorbachev/workflowy-api"
keywords = []
categories = []
exclude = [
    ".*",
    "*.local.*",
    "doc/dev",
    "specs",
    "AGENTS.ts",
    "CargoMetadata.ts",
    "README.ts",
    "AGENTS*.md",
    "CLAUDE*.md",
    "deno.lock",
    "deno.json",
    "commitlint.config.mjs",
    "fnox.toml",
    "mise.toml",
    "rumdl.toml",
    "rustfmt.toml",
    ".yolobox"
]

[workspace.metadata.details]
name = "workflowy-api"
title = "Workflowy API client"
readme = { generate = true }

[workspace.lints.rust]
redundant_imports = "deny"
unused_import_braces = "deny"
# unused_qualifications must not be "deny" because our code style has multiple `use Foo::*;`, and some macros (derive_more::Display, strum::Display, strum::EnumString) produce code with full qualifications
# unused_qualifications = "deny"

[workspace.lints.clippy]
absolute_paths = "deny"
arithmetic_side_effects = "deny"

[package]
name = "workflowy-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Workflowy API client."
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
exclude.workspace = true

[package.metadata.details]
title = "Workflowy API client"

[lints]
workspace = true

[dependencies]
derive_more = { version = "2", features = ["full"] }
errgonomic = "0.5"
governor = "0.10"
reqwest = { version = "0.13", features = ["json", "query"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
timestamp-please = { version = "0.2", features = ["serde"] }
url = "2"
url-macro = "0.2"

[dev-dependencies]
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
static-env-var = "0.1.0"
