#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"

[providers]
keychain = { type = "keychain", service = "workflowy-api" }
pass = { type = "password-store", prefix = "workflowy-api/" }

[profiles]

[profiles.test]

[profiles.test.secrets]
WORKFLOWY_API_KEY= { provider = "pass", value = "TEST_WORKFLOWY_API_KEY" }
