#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"
env = "exec"

[providers]
keychain = { type = "keychain", service = "workflowy-api" }
age = { type = "age", recipients = ["age1sf4r4amev2svqr6llwg8hgtz9n7p5qdh7hh0mavcshzfrmgfduksnq3hql","age1605gsnxpe536sprwccyumq74veg0g80u55n8ggems0t8deau6qdsfnq3m3","age15xqfgqu79etfnd047vkaypq4h3nh56xw6kywhn7uwhrdylmlyd4q0r9a3z"]}

[profiles]

[profiles.test]

[profiles.test.secrets]
WORKFLOWY_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cEZBT0ZBS1hvWjZ1TmRTU3JNWFd0SHRJR2haNy9lVitJYmdYWUNwWFFFClRNbHZ1RVhON0F3TUFaL2d3VjVSZ0ZpQTNkYmJ4eWY4UTkwOHZ5MldPQVEKLT4gWDI1NTE5IHFxdnRsWHVBS1lvVGpUeUJOT25FSTBjUWROYjhjVDV4bDlZNXFRK3I5bUEKNndoUWFjYlJiUHcxdzJzRVZJNHJWT00xeGZrc3RtdUJtMXkxUitjR2ZjZwotPiBYMjU1MTkgWlFhOStHVzA2K3c4enF6VElHdDhIVzVVeW12cU5GMDZKRmdTbHBZbjNVYwpHckJnNktyNmVLZXpXUkpZL1V2TzEzR0RjbVE4R1VBcGJ3V0MwRTJNS1dvCi0+IHkjUDYtZ3JlYXNlCkhFb1U4b05NdHRJVTRDam0rVWh5N0dMdlFXSW1ZYVp3RC96bHpWV3Nodm00MGI4Zy9BYS84WGRPSWNWclFoVkMKS3QrVwotLS0gNVhGR1lBMTN4YnYzdGNjaFR5czU5UkFsT1MyT205L3Z6dVBUdUNESUlxNAr523ZyZuuZz7AUEFJerO03E/bd+x7M9d639mxBYthjU/BtxzVa9pMyR+ahceM0d9EC0PZ9z/hYBp/Lrhou5VBnIT51q93VfAM=" }
